#numpy array copy and view

1. Create a NumPy array and make a copy of it. Modify the original array and print both
the original and copied arrays.

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=a.copy()
print(a)
b[2]=20
print(b)

[1 2 3 4]
[ 1  2 20  4]


2. Create a view of a NumPy array. Modify the view and print both the original and the
view. How do the results compare to using a copy?


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=a.view()
b[2]=6
print(a)
print(b)

[1 2 6 4]
[1 2 6 4]


Explain the difference between array.copy() and array.view() in NumPy. Provide an
example to illustrate the difference.

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
c=a.copy()
a[0]=10
d=b.view()
b[0]=20
print(c.base)
print(d.base)

None
[20  2  3  4  5]


4. Create a 2D NumPy array and generate a view that represents only the first row.
Modify this view and print the changes in both the original array and the view.

#check copy or view

In [ ]:
a=np.array([[1,2],[3,4]])
b=a[0]
c=a.view()
a[0,1]=10
print(a)
print(b)

[[ 1 10]
 [ 3  4]]
[ 1 10]


5. Create a NumPy array and another array by slicing the first array. Check whether the
second array is a copy or a view of the first array.

In [ ]:
a=np.array([[1,2],[3,4]])
b=a[0]
print(a)
print(b)
print(b.base)


[[1 2]
 [3 4]]
[1 2]
[[1 2]
 [3 4]]


6. Use the np.may_share_memory() function to check if two arrays share the same
memory. Provide an example.

In [ ]:
a=np.array([1,2,3])
b=a.view()
print(np.may_share_memory(a,b))

True


7. Create a NumPy array, then use the reshape() function on it. Check whether the
reshaped array is a view or a copy.

In [ ]:
a=np.array([1,2,3,4,5,6])
b=a.reshape(2,3)
print(np.shares_memory(a,b))
#reshaping creats a view,so share_memory return true
#or use base
print(b.base)

True
[1 2 3 4 5 6]


#numpy array shape

8. Create a NumPy array and print its shape. Then reshape it to another valid shape and
print the new shape.

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)
a.reshape(-1,3)
print(a)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


9. Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it
into a 3D array. Print the shapes at each step.

In [ ]:
import numpy as np
a=np.arange(1,13)
b=a.reshape(-1,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
a=np.arange (12).reshape(3,4)
b=a.reshape